import { Inter } from "next/font/google";
import "./globals.css";
import { Registry as StyledComponetRegistry } from "@/style/registry";
import Header from "@/components/Headers";
import SnsButtons from "@/components/SnsButtons";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <SnsButtons/>
          <Header/>
          <StyledComponetRegistry>
            {children}
          </StyledComponetRegistry>
          
        
        </body>
    </html>
  );
}
